### ISSUE TITLE
A lot of depreciations

### ISSUE THREAD

**Issue by drchibs** [linkpreview/linkpreview#14]
the package doesn't install with npm because a lot of its dependencies are depreciated or moved to another address.

please address this issue asap
thanks.

**Comment by bring2dip** [comment]
@drchibs I'm sorry for late reply and couldn't take out my time to fix dependencies. 
https://github.com/linkpreview/linkpreview/pull/16 Here's this PR should fix deprecations and warnings

**Comment by drchibs** [comment]
Thank you @bring2dip 
I'll check it out
